[meta]
id = "imgbb"

[request]
method = "POST"
url = "https://api.imgbb.com/1/upload"

[request.params]
key = "{config.key}"

[request.headers]
User-Agent = "upgit"

[request.body]
key = { type = "string", value = "{config.key}" }
image = { type = "file_base64" }
format = { type = "string", value = "json" }

[response]
url = { from = "json", path = "data.url" }
