[meta]
id = "imgurlorg"

[request]
method = "POST"
url = "https://imgurl.org/upload/ftp"

[request.headers]
User-Agent = "upgit"

[request.body]
file = { type = "file" }

[response]
url = { from = "json", path = "url" }
