[package]
name = "upgit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
arboard = "3"
chrono = { version = "0.4", default-features = false, features = ["std"] }
clap = { version = "4", features = ["derive"] }
png = "0.17"
serde_json = "1"
tempfile = "3"
upgit-core = { path = "../upgit-core", version = "0.3.0-beta.2" }
upgit-uploaders = { path = "../upgit-uploaders", version = "0.3.0-beta.2" }

[target.'cfg(windows)'.dependencies]
clipboard-win = "5"

[dev-dependencies]
clap = { version = "4", features = ["derive"] }
tempfile = "3"
